### ISSUE TITLE
Segmentation fault during upload_block_async

### ISSUE THREAD

**Issue by upcbharat** [Azure/azure-storage-cpp#265]
Hi,

We have seen the below crash in azure library recently.
Azure Storage Client Library for C++ (3.0.0)

Please let me known if there is any fix.

Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/opt/qorestor/bin/ocafsd --node_no=0 --rpcport=9911 --dictdir= --nvm_journal_pa'.
Program terminated with signal 11, Segmentation fault.
#0  _M_lower_bound (this=<optimized out>, __k=<synthetic pointer>, __y=0x7fb4d666a4c0, __x=0x6c656e6e) at /usr/include/c++/4.8.2/bits/stl_tree.h:1141
1141    /usr/include/c++/4.8.2/bits/stl_tree.h: No such file or directory.

Missing separate debuginfos, use: debuginfo-install storage-server-6.0.0-511.x86_64
(gdb) bt
#0  _M_lower_bound (this=<optimized out>, __k=<synthetic pointer>, __y=0x7fb4d666a4c0, __x=0x6c656e6e) at /usr/include/c++/4.8.2/bits/stl_tree.h:1141
#1  find (__k=<synthetic pointer>, this=0x7fadfc5f9000 <Signals>) at /usr/include/c++/4.8.2/bits/stl_tree.h:1792
#2  find (__x=<synthetic pointer>, this=0x7fadfc5f9000 <Signals>) at /usr/include/c++/4.8.2/bits/stl_map.h:822
#3  StackTrace::errorHandler (signalCode=11) at ../ScErrorHandler.h:39
#4  <signal handler called>
#5  0x00007fb4e08574dc in std::_Rb_tree<std::string, std::pair<std::string const, std::shared_ptr<web::http::client::http_client> >, std::_Select1st<std::pair<std::string const, std::shared_ptr<web::http::client::http_client> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::shared_ptr<web::http::client::http_client> > > >::find(std::string const&) ()
   from /usr/local/libs/usr/lib/libazurestorage.so.3
#6  0x00007fb4e08522b7 in azure::storage::core::http_client_reusable::get_http_client(web::uri const&, web::http::client::http_client_config const&) () from /usr/local/libs/usr/lib/libazurestorage.so.3
#7  0x00007fb4e08c2eff in azure::storage::core::executor_impl::execute_async(std::shared_ptr<azure::storage::core::storage_command_base>, azure::storage::request_options const&, azure::storage::operation_context)::{lambda()#1}::operator()() const () from /usr/local/libs/usr/lib/libazurestorage.so.3
#8  0x00007fb4e08c38ec in std::_Function_handler<pplx::task<bool> (), azure::storage::core::executor_impl::execute_async(std::shared_ptr<azure::storage::core::storage_command_base>, azure::storage::request_options const&, azure::storage::operation_context)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from /usr/local/libs/usr/lib/libazurestorage.so.3
#9  0x00007fb4e08c152c in azure::storage::core::executor_impl::execute_async(std::shared_ptr<azure::storage::core::storage_command_base>, azure::storage::request_options const&, azure::storage::operation_context) () from /usr/local/libs/usr/lib/libazurestorage.so.3
#10 0x00007fb4e0996fe3 in std::_Function_handler<pplx::task<void> (azure::storage::core::istream_descriptor), azure::storage::cloud_block_blob::upload_block_async(std::string const&, Concurrency::streams::basic_istream<unsigned char>, std::string const&, azure::storage::access_condition const&, azure::storage::blob_request_options const&, azure::storage::operation_context) const::{lambda(azure::storage::core::istream_descriptor)#1}>::_M_invoke(std::_Any_data const&, azure::storage::core::istream_descriptor) () from /usr/local/libs/usr/lib/libazurestorage.so.3
#11 0x00007fb4e09a440e in std::function<pplx::task<void> (azure::storage::core::istream_descriptor)>::operator()(azure::storage::core::istream_descriptor) const ()
   from /usr/local/libs/usr/lib/libazurestorage.so.3
#12 0x00007fb4e099d341 in pplx::task<azure::storage::core::istream_descriptor>::_ContinuationTaskHandle<azure::storage::core::istream_descriptor, void, azure::storage::cloud_block_blob::upload_block_async(std::string const&, Concurrency::streams::basic_istream<unsigned char>, std::string const&, azure::storage::access_condition const&, azure::storage::blob_request_options const&, azure::storage::operation_context) const::{lambda(azure::storage::core::istream_descriptor)#1}, std::integral_constant<bool, false>, pplx::details::_TypeSelectorAsyncTask>::_Continue(std::integral_constant, std::integral_constant<bool, false>::_TypeSelectorAsyncOperationOrTask) const [clone .isra.1705] () from /usr/local/libs/usr/lib/libazurestorage.so.3
#13 0x00007fb4e099d605 in pplx::details::_PPLTaskHandle<unsigned char, pplx::task<azure::storage::core::istream_descriptor>::_ContinuationTaskHandle<azure::storage::core::istream_descriptor, void, azure::storage::cloud_block_blob::upload_block_async(std::string const&, Concurrency::streams::basic_istream<unsigned char>, std::string const&, azure::storage::access_condition const&, azure::storage::blob_request_options const&, azure::storage::operation_context) const::{lambda(azure::storage::core::istream_descriptor)#1}, std::integral_constant<bool, false>, pplx::details::_TypeSelectorAsyncTask>, pplx::details::_ContinuationTaskHandleBase>::invoke() const () from /usr/local/libs/usr/lib/libazurestorage.so.3
#14 0x0000000000b6e04f in pplx::details::_TaskProcHandle::_RunChoreBridge (_Parameter=0x7fb4d63a7a00) at ../casablanca/Release/include/pplx/pplx.h:116
#15 0x00007fb4e0f5c4b1 in boost::asio::detail::completion_handler<boost::_bi::bind_t<void, void (void*), boost::_bi::list1<boost::_bi::value<void*> > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) () from /usr/local/libs/usr/lib/libcpprest.so.2.9
#16 0x00007fb4e0ee9be1 in boost::asio::detail::task_io_service::run(boost::system::error_code&) () from /usr/local/libs/usr/lib/libcpprest.so.2.9
#17 0x00007fb4e0f5bd76 in (anonymous namespace)::threadpool_impl::thread_start(void*) () from /usr/local/libs/usr/lib/libcpprest.so.2.9
#18 0x00007fb4ded62dd5 in start_thread () from /lib64/libpthread.so.0
#19 0x00007fb4de875f6d in clone () from /lib64/libc.so.6
(gdb)

Thanks

**Comment by katmsft** [comment]
Several segfault issue has already been identified after 3.0.0 and fixed. Can you try the latest version to see if the issue persist?

**Comment by JinmingHu-MSFT** [comment]
We're going to close this issue because of inactivity, feel free to reopen it if you have any further questions.
